/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/check-domain/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Domain
         * @description Validate URL, prefer root domain but fallback to www if needed.
         */
        get: operations["check_domain_check_domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/startups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Startups */
        get: operations["list_startups_startups__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/startups/{startup_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Startup */
        get: operations["get_startup_startups__startup_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/startups/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Startup */
        get: operations["lookup_startup_startups_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckDomainResponse */
        CheckDomainResponse: {
            /** Exists */
            exists: boolean;
            /** Normalized */
            normalized?: string | null;
            /** Error */
            error?: string | null;
            /** Note */
            note?: string | null;
            /** Hostname */
            hostname?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Startup */
        Startup: {
            /** Id */
            id?: number | null;
            /** Company Name */
            company_name: string;
            /** Company Website */
            company_website?: string | null;
            /**
             * Year Founded
             * @default [
             *       null
             *     ]
             */
            year_founded: string | null;
            /**
             * Country
             * @default [
             *       null
             *     ]
             */
            country: string | null;
            /** Num Employees */
            num_employees?: string | null;
            /** Founders */
            founders?: {
                [key: string]: string | null;
            } | null;
            /** Investors */
            investors?: string[] | null;
            /** Funding Stage */
            funding_stage?: string | null;
            /** Funds Raised */
            funds_raised?: string | null;
            /** Ref Funding */
            ref_funding?: string[] | null;
            /** Tech Offering */
            tech_offering?: string | null;
            /** Ref Tech */
            ref_tech?: string[] | null;
            /** Tech Embedding */
            tech_embedding?: number[] | null;
            /** Uvp */
            uvp?: string | null;
            /** Ref Uvp */
            ref_uvp?: string[] | null;
            /** Uvp Embedding */
            uvp_embedding?: number[] | null;
            /** Trl */
            trl?: string | null;
            /** Trl Explanation */
            trl_explanation?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    check_domain_check_domain__get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDomainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_startups_startups__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Startup"][];
                };
            };
        };
    };
    get_startup_startups__startup_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                startup_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Startup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_startup_startups_lookup_get: {
        parameters: {
            query: {
                startup_url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Startup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
